spring:
  profiles: mysql
  datasource:
    url: jdbc:mysql://ph1090-haproxy:3306
    username: jt
    password: dink9944
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLInnoDBDialect

---

spring:
  profiles: oracle
  datasource:
    url: jdbc:oracle://localhost:3306
    username: sys
    password: dink9944
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDBDialect